version: '3.4'
networks:
  personskillsapi:
    driver: bridge

services:
  dbpersonskills:
    container_name: dbpersonskills
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345#  
    networks:
      - personskillsapi
  
  webapipersonskills:
    image: ${DOCKER_REGISTRY-}webapipersonskills
    build:
      context: .
      dockerfile: WebApiPersonSkills/Dockerfile
    ports:
      - 8001:80 
    depends_on:
      - dbpersonskills
    environment:
      - DB_HOST=dbpersonskills
      - DB_NAME=persondb
      - DB_PASSWORD=password@12345# 
    networks:
      - personskillsapi

